version: "3.7"
services:
  # Webserver
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    environment:
      - TZ=Europe/Stockholm
    ports: 
      - "8080:80"
    networks:
      - internal
    restart: on-failure
    depends_on:
      - php 
    volumes:
      - web:/var/www      
  # PHP engine
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal client_port=9003
      - TZ=Europe/Stockholm
    volumes:
      - web:/var/www
    restart: on-failure      
    depends_on:
      - mysql
  # MySQL database
  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    networks:
      - internal      
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql   
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=Europe/Stockholm      
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
  # MySQL database web UI
  #adminer:
  #  image: adminer
  #  restart: on-failure
  #  ports:
  #    - 8082:8080
  #  depends_on:
  #    - mysql
networks:
  internal:
    driver: bridge
volumes:
  web:
    name: ${PROJECT}
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${PROJECT_DIR}'
  db:
    external: false
    name: ${PROJECT}_DB